project:
  packs:
    - pack: Nuvoton::NuMicroM33_DFP
  setups:
    - output:
        # bin, elf, hex, lib
        type: ["elf", "bin"]
      add-path:
        - ../../../../../Library/Device/Nuvoton/m3331/Include
        - ../../../../../Library/StdDriver/inc
        - ../../../../../Library/CMSIS/Core/Include
        - ../../common/inc
      misc:
        - for-compiler: AC6
          C:
            - -std=c99 -fno-rtti -funsigned-char -fshort-enums -fshort-wchar -ffunction-sections -fdata-sections -w -fno-inline
            - -D__MICROLIB
          ASM:
            - -masm=auto
          Link:
            - --library_type=microlib --map --load_addr_map_info --symbols
            - --info sizes --info totals --strict --summary_stderr --info summarysizes
        - for-compiler: GCC
          C:
            - -std=gnu11 -mthumb -masm-syntax-unified -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections
          Link:
            - -mthumb -fmessage-length=0 -fsigned-char --specs=nano.specs --specs=nosys.specs
            - -Wl,--gc-sections,-Map="$elf()$.map"
    - setup: Options for App
      output :
        base-name: App
      for-context: .App
      linker:
        - script: ./App.sct
          for-compiler: AC6
        - script: ./App.ld
          for-compiler: GCC
    - setup: Options for NewApp
      output :
        base-name: NewApp
      for-context: .NewApp
      define:
        - NewApp
      linker:
        - script: ./App.sct
          for-compiler: AC6
        - script: ./App.ld
          for-compiler: GCC
  groups:
    - group: CMSIS
      files:
        - file: ../../../../../Library/Device/Nuvoton/m3331/Source/startup_m3331.c
          for-compiler: AC6
        - file: ../../../../../Library/Device/Nuvoton/m3331/Source/startup_m3331.c
          for-compiler: GCC
        - file: ../../../../../Library/Device/Nuvoton/m3331/Source/system_m3331.c
    - group: Library
      files:
        - file: ../../../../../Library/StdDriver/src/retarget.c
        - file: ../../../../../Library/StdDriver/src/uart.c
        - file: ../../../../../Library/StdDriver/src/sys.c
        - file: ../../../../../Library/StdDriver/src/clk.c
        - file: ../../../../../Library/StdDriver/src/fmc.c
        - file: ../../../../../Library/StdDriver/src/wdt.c
    - group: User
      files:
        - file: ../main.c